### ISSUE TITLE
Unindented block and global options

### ISSUE THREAD

**Issue by kiarn** [haginara/ssh_config#14]
Hello @haginara 

Thanks for this useful lib. 
I just found out that `ssh_config` does not support global options at the beginning of the file and unindented block ( indenting a block is always a good practice, but it's not required in the ssh config file ).

Here a dummy example of config file which leads to a `WrongSSHConfig` : 

```
CanonicalizeHostname no
CanonicalDomains no

Host github.com
    User git
    IdentityFile ~/.ssh/id_github
```  

or simply

```
Host github.com
User git
IdentityFile ~/.ssh/id_github
```  

But both files have a "good" syntax.

I tried to modify the pattern defined with `pyparsing` in order to parse the unindented global options, but it only works partially : 

```python
    def parse(self, data=""):
        """Parse ssh-config data

        args:
            data (str)

        returns:
            Parsed config or None (dict)
        """

        if data:
            self.raw = data

        SPACE = White().suppress()
        SEP = Suppress(SPACE) | Suppress("=")
        HOST = CaselessLiteral("Host").suppress()
        MATCH = CaselessLiteral("Match").suppress()
        KEY = Word(alphanums)
        VALUE = Word(alphanums + ' ~%*?!._-+/,"')
        paramValueDef = SkipTo("#" | lineEnd)
        indentStack = [1]

        HostDecl = (HOST | MATCH) + SEP + VALUE
        paramDef = Dict(Group(~HOST + KEY + SEP + paramValueDef))
        block = indentedBlock(paramDef, indentStack)
        HostBlock = Dict(Group(HostDecl + block))
        Begin = Empty().setParseAction(replaceWith("GLOBAL_OPTIONS"))
        GlobalOptions = Group(ZeroOrMore(Dict(Group(paramDef))))
        try:
            return (Begin + GlobalOptions + OneOrMore(HostBlock)).ignore(pythonStyleComment).parseString(self.raw)
        except ParseException as e:
            print(e)
        return None
```
The idea is to parse an eventual first unindented block without host definition, and add the keyword `"GLOBAL_OPTIONS"` to this block in order to have a proper dict.

It seems to work with the parsed object, but not for the conversion `.asDict()` : 

```python
# parsed :
['GLOBAL_OPTIONS', [[['CanonicalizeHostname', 'no']], [['CanonialDomains', 'no']]], ['github.com', [[['User', 'git']], [['IdentityFile', '~/.ssh/id_github']]]]]

# parsed.asDict() : 
{'github.com': [{'User': 'git'}, {'IdentityFile': '~/.ssh/id_github'}]}
```

The block `"GLOBAL_OPTIONS"` appears correctly in the object, but is not converted in the resulted dict.
Since I don't know the lib `pyparsing` very well, there's maybe an easier way to achieve this, and maybe you have a better idea for this, it would be great.

Thanks

Arnaud

**Comment by haginara** [comment]
HI @kiarn
Appreciate to bring up the issue and suggest the idea.
I've decided to replace the pyparsing.

https://github.com/haginara/ssh_config/pull/19

It supports the unindented block attributes(options) and also parse the global options.
But it's not fully supporting the global options yet.
